worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    access_log  /dev/stdout;
    error_log   /dev/stderr warn;

        server {
            listen 80;
            server_name local.artembay.ru;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

                error_page 401 @unauthorized;
                location @unauthorized {
                        default_type application/json;
                        return 401 '{"error": "Unauthorized: Bearer token is missing"}';
                }

            location = /api/v2/login {
                proxy_pass http://api:6644;
            }

        location = /api/v2/refresh {
            proxy_pass http://api:6644;
        }

            location = /api/v2/revoke {
                if ($http_authorization !~* "^Bearer ") {
                    return 401;
                }
                proxy_pass http://api:6644;
            }

            location ^~ /api/v2/sync/ {
                if ($http_authorization !~* "^Bearer ") {
                    return 401;
                }
                proxy_pass http://api:6644;
            }

            location /api/v2/ {
                # Whitelist your server ip there
                allow 127.0.0.1/32;
                deny all;
                proxy_pass http://api:6644;
            }

            location / {
                return 404;
            }
        }
}